import { db } from "./db";

/**
 * Exports the entire IndexedDB content as a JSON blob
 */
export async function exportFullDatabase(): Promise<Blob> {
  const tables = await Promise.all(
    db.tables.map(async (table) => ({
      name: table.name,
      data: await table.toArray(),
    }))
  );

  const exportData = {
    version: 1,
    timestamp: new Date().toISOString(),
    tables: Object.fromEntries(tables.map((t) => [t.name, t.data])),
  };

  return new Blob([JSON.stringify(exportData, null, 2)], {
    type: "application/json",
  });
}

/**
 * Triggers a download of the database export
 */
export function downloadBackup(blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 16);
  a.href = url;
  a.download = `PEQ_Backup_${timestamp}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Resets all tables in the database (Dangerous!)
 */
export async function resetDatabase() {
  await db.transaction("rw", db.tables, async () => {
    await Promise.all(db.tables.map((table) => table.clear()));
  });
}

/**
 * Imports a JSON backup into the database (Overwrites!)
 * Expects the format generated by exportFullDatabase
 */
export async function importDatabase(jsonData: string) {
  const parsed = JSON.parse(jsonData);

  if (!parsed.tables || typeof parsed.tables !== "object") {
    throw new Error("Format de sauvegarde invalide : Tables manquantes.");
  }

  await db.transaction("rw", db.tables, async () => {
    // Clear all existing data first
    await Promise.all(db.tables.map((table) => table.clear()));

    // Restore each table
    for (const [tableName, data] of Object.entries(parsed.tables)) {
      const table = db.table(tableName);
      if (table) {
        await table.bulkAdd(data as any[]);
      }
    }
  });
}
